import 'package:flutter/material.dart';

import '../../../../core/widgets/responsive_dialog_shell.dart';
import '../../models/finance_account_model.dart';
import '../../models/finance_category_model.dart';
import '../../models/finance_income_model.dart';
import '../../services/finance_service.dart';

class AddIncomeDialog extends StatefulWidget {
  const AddIncomeDialog({super.key, this.initial});

  final FinanceIncomeModel? initial;

  @override
  State<AddIncomeDialog> createState() => _AddIncomeDialogState();
}

class _AddIncomeDialogState extends State<AddIncomeDialog> {
  final _formKey = GlobalKey<FormState>();
  final _title = TextEditingController();
  final _amount = TextEditingController();
  final _reference = TextEditingController();
  final _remarks = TextEditingController();
  final _service = FinanceService();
  String? _categoryId;
  String _programType = 'tuition';
  String? _accountId;
  String _paymentMode = 'cash';
  DateTime _date = DateTime.now();
  bool _saving = false;

  bool get _isEdit => widget.initial != null;
  /// Locked (view-only) when editing an entry that was generated by a Fee
  /// Collection — its fields are owned by that collection (see
  /// FinanceService.updateIncome's doc comment). Not locked when creating
  /// new, since new entries here are never Fee-sourced.
  bool get _isFeeSourced => widget.initial?.sourceModule == 'fees';

  @override
  void initState() {
    super.initState();
    final initial = widget.initial;
    if (initial != null) {
      _title.text = initial.title;
      _amount.text = initial.amount.toStringAsFixed(0);
      _reference.text = initial.referenceNo;
      _remarks.text = initial.remarks;
      _categoryId = initial.categoryId.isEmpty ? null : initial.categoryId;
      _programType = initial.programType.isEmpty ? 'tuition' : initial.programType;
      _accountId = initial.accountId.isEmpty ? null : initial.accountId;
      _paymentMode = initial.paymentMode.isEmpty ? 'cash' : initial.paymentMode;
      _date = initial.incomeDate ?? DateTime.now();
    }
  }

  Future<void> _pickDate() async {
    final picked = await showDatePicker(
      context: context,
      firstDate: DateTime(2000),
      lastDate: DateTime(2100),
      initialDate: _date,
    );
    if (picked != null) setState(() => _date = picked);
  }

  @override
  void dispose() {
    _title.dispose();
    _amount.dispose();
    _reference.dispose();
    _remarks.dispose();
    super.dispose();
  }

  Future<void> _save() async {
    if (_isFeeSourced) return;
    if (!(_formKey.currentState?.validate() ?? false)) return;
    setState(() => _saving = true);
    try {
      final categories = await _service.watchCategories().first;
      final accounts = await _service.watchAccounts().first;
      final cat = categories.firstWhere((c) => c.id == _categoryId);
      final acc = accounts.firstWhere((a) => a.id == _accountId);
      final amount = double.tryParse(_amount.text.trim()) ?? 0;

      final initial = widget.initial;
      if (initial != null) {
        await _service.updateIncome(
          id: initial.id,
          title: _title.text.trim(),
          categoryId: cat.id,
          categoryName: cat.name,
          amount: amount,
          date: _date,
          paymentMode: _paymentMode,
          referenceNo: _reference.text.trim(),
          remarks: _remarks.text.trim(),
        );
      } else {
        final now = DateTime.now();
        final model = FinanceIncomeModel(
          id: '',
          title: _title.text.trim(),
          categoryId: cat.id,
          categoryName: cat.name,
          programType: _programType,
          studentId: '',
          studentName: '',
          classId: '',
          className: '',
          amount: amount,
          incomeDate: _date,
          paymentMode: _paymentMode,
          accountId: acc.id,
          accountName: acc.name,
          referenceNo: _reference.text.trim(),
          remarks: _remarks.text.trim(),
          attachmentUrls: const [],
          ledgerEntryId: '',
          createdAt: now,
          updatedAt: now,
          createdBy: 'admin',
        );
        await _service.createIncome(model);
      }
      if (!mounted) return;
      Navigator.pop(context, true);
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(_isEdit ? 'Failed to update income: $e' : 'Failed to save income')),
      );
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final locked = _isFeeSourced;
    return ResponsiveDialogShell(
      desktopWidth: 720,
      desktopHeight: 680,
      child: Form(
          key: _formKey,
          child: SingleChildScrollView(
            padding: const EdgeInsets.all(20),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(_isEdit ? 'Edit Income' : 'Add Income', style: Theme.of(context).textTheme.titleLarge),
                const SizedBox(height: 16),
                if (locked)
                  Padding(
                    padding: const EdgeInsets.only(bottom: 12),
                    child: Text(
                      'This entry was generated from a Fee Collection, so it cannot be '
                      'edited here. Edit or void the Fee Collection in the Fees module '
                      'instead — this entry updates automatically.',
                      style: TextStyle(fontSize: 12, color: Colors.grey.shade700),
                    ),
                  ),
                TextFormField(
                  controller: _title,
                  enabled: !locked,
                  decoration: const InputDecoration(labelText: 'Title'),
                  validator: (v) => (v == null || v.trim().isEmpty) ? 'Required' : null,
                ),
                const SizedBox(height: 12),
                StreamBuilder<List<FinanceCategoryModel>>(
                  stream: _service.watchCategories(),
                  builder: (context, snap) {
                    final items = snap.data?.where((e) => e.type == 'income' && e.isActive).toList() ?? [];
                    return DropdownButtonFormField<String>(
                      initialValue: _categoryId,
                      decoration: const InputDecoration(labelText: 'Category'),
                      items: items.map((e) => DropdownMenuItem(value: e.id, child: Text(e.name))).toList(),
                      onChanged: locked ? null : (v) => setState(() => _categoryId = v),
                      validator: (v) => v == null ? 'Required' : null,
                    );
                  },
                ),
                const SizedBox(height: 12),
                DropdownButtonFormField<String>(
                  initialValue: _programType,
                  decoration: const InputDecoration(labelText: 'Program Type'),
                  items: const ['tuition', 'after_school', 'day_care', 'training', 'phonics', 'material', 'uniform', 'transport', 'other']
                      .map((e) => DropdownMenuItem(value: e, child: Text(e)))
                      .toList(),
                  // Not part of updateIncome — informational only once
                  // editing (kept from creation, not user-editable here).
                  onChanged: (locked || _isEdit) ? null : (v) => setState(() => _programType = v ?? 'tuition'),
                ),
                const SizedBox(height: 12),
                TextFormField(
                  controller: _amount,
                  enabled: !locked,
                  decoration: const InputDecoration(labelText: 'Amount'),
                  keyboardType: TextInputType.number,
                  validator: (v) => (double.tryParse(v ?? '') ?? 0) > 0 ? null : 'Enter amount',
                ),
                const SizedBox(height: 12),
                ListTile(
                  contentPadding: EdgeInsets.zero,
                  title: const Text('Date'),
                  subtitle: Text(_date.toIso8601String().split('T').first),
                  trailing: TextButton(
                    onPressed: locked ? null : _pickDate,
                    child: const Text('Change'),
                  ),
                ),
                DropdownButtonFormField<String>(
                  initialValue: _paymentMode,
                  decoration: const InputDecoration(labelText: 'Payment Mode'),
                  items: const ['cash', 'upi', 'bank_transfer', 'cheque', 'other']
                      .map((e) => DropdownMenuItem(value: e, child: Text(e)))
                      .toList(),
                  onChanged: locked ? null : (v) => setState(() => _paymentMode = v ?? _paymentMode),
                ),
                const SizedBox(height: 12),
                StreamBuilder<List<FinanceAccountModel>>(
                  stream: _service.watchAccounts(),
                  builder: (context, snap) {
                    final items = snap.data?.where((e) => e.isActive).toList() ?? [];
                    return DropdownButtonFormField<String>(
                      initialValue: _accountId,
                      decoration: InputDecoration(
                        labelText: 'Account',
                        helperText: _isEdit ? 'Account cannot be changed once created' : null,
                      ),
                      items: items.map((e) => DropdownMenuItem(value: e.id, child: Text(e.name))).toList(),
                      // Account is intentionally not editable — see
                      // FinanceService.updateIncome's doc comment.
                      onChanged: (locked || _isEdit) ? null : (v) => setState(() => _accountId = v),
                      validator: (v) => v == null ? 'Required' : null,
                    );
                  },
                ),
                const SizedBox(height: 12),
                TextFormField(
                  controller: _reference,
                  enabled: !locked,
                  decoration: const InputDecoration(labelText: 'Reference No'),
                ),
                const SizedBox(height: 12),
                TextFormField(
                  controller: _remarks,
                  enabled: !locked,
                  decoration: const InputDecoration(labelText: 'Remarks'),
                  maxLines: 3,
                ),
                const SizedBox(height: 20),
                Row(
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: [
                    TextButton(
                      onPressed: _saving ? null : () => Navigator.pop(context),
                      child: Text(locked ? 'Close' : 'Cancel'),
                    ),
                    if (!locked) const SizedBox(width: 8),
                    if (!locked)
                    FilledButton(
                      onPressed: _saving ? null : _save,
                      child: _saving
                          ? const SizedBox(
                              width: 16,
                              height: 16,
                              child: CircularProgressIndicator(strokeWidth: 2),
                            )
                          : const Text('Save'),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
    );
  }
}
