import 'firebase_options_dev.dart';
import 'main.dart';

/// Dev entrypoint — boots against the real `twod-montessori-dev` Firebase
/// project (see [DefaultFirebaseOptions], generated by `flutterfire
/// configure --project=twod-montessori-dev`) instead of the local
/// Emulator Suite. Run/build with:
///
///   flutter run -d chrome -t lib/main_dev.dart
///   flutter build web -t lib/main_dev.dart
///
/// `useEmulators: false` is what actually makes this build talk to the
/// real backend — see `main.dart`'s [bootstrapAndRunPublicWebApp] and
/// `packages/firebase_adapters/lib/src/firebase_bootstrap.dart`.
Future<void> main() async {
  await bootstrapAndRunPublicWebApp(
    options: DefaultFirebaseOptions.currentPlatform,
    useEmulators: false,
  );
}
