name: 🚀 Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web (PROD)
        run: flutter build web --release --dart-define=APP_ENV=prod

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Setup Firebase Auth
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-service-account.json

      - name: Deploy to Firebase
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=firebase-service-account.json
          firebase deploy --only hosting 2>&1 | tee firebase-deploy.log

          EXIT_CODE=${PIPESTATUS[0]}

          if [ $EXIT_CODE -ne 0 ]; then
            if grep -q "current active version" firebase-deploy.log; then
              echo "Firebase Hosting version is already active. Treating as success."
              exit 0
            fi

            exit $EXIT_CODE
          fi
