name: 🚀 Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Upgrade Flutter
        run: |
          flutter upgrade
          flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web (PROD)
        run: flutter build web --release

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Setup Firebase Auth
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-service-account.json

      - name: Deploy to Firebase
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=firebase-service-account.json
          firebase deploy --only hosting
